### ISSUE TITLE
"Error: Error watching file for changes: EMFILE" when launching tests with "npm test"

### ISSUE THREAD

**Issue by juanmaguitar** [reactstrap/reactstrap#1073]
### Issue description

- components: all
- reactstrap version `6.1.0`

### What is happening?

```
⬢  reactstrap  master ⦿ npm test

> reactstrap@6.1.0 test /PROJECTS/reactstrap
> cross-env BABEL_ENV=test react-scripts test --env=jsdom

2018-06-15 20:37 node[61784] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-06-15 20:37 node[61784] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-06-15 20:37 node[61784] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
```

### What should be happening?

It should launch the tests properly

### Steps to reproduce issue

1. clone the repo
2. install the dependencies with `npm install`
3. launch the tests with `npm test`

### References

- https://github.com/facebook/create-react-app/issues/2393
- https://stackoverflow.com/questions/41657754/testing-with-jest-failed-with-error-error-watching-file-for-changes-emfile#41661452

**Comment by juanmaguitar** [comment]
It seems to be a jest issue. As many people in [this issue](https://github.com/facebook/jest/issues/3436) doing `brew install watchman` solved this for me.

I don't know if there's some more generic solution that should be adopted by reactstrap to prevent this error
