### ISSUE TITLE
TypeError: Cannot read property 'setReferenceNode' of undefined

### ISSUE THREAD

**Issue by anujm249** [reactstrap/reactstrap#1499]
- components: `DropdownMenu `
- reactstrap version `^8.0.0`
- import method `umd/csj/es` 
- react version `16.8.6`

### What is happening?

I am using reactstrap with next js. All component are getting rendered on the server side.

500 Internal Server Error. on page loading

DropdownMenu is using react-popper which is causing the issue. 
This work fines while development as component rendering on the client side.

### Error message in console

main-541f01c65744a5c2c60b.js:1 {name: "Internal Server Error.", message: "500 - Internal Server Error.", statusCode: 500}

```

TypeError: Cannot read property 'setReferenceNode' of undefined
0|fd     |     at Object.children (/webapps/node_modules/react-popper/lib/cjs/Reference.js:62:33)
0|fd     |     at a.render (/webapps/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
0|fd     |     at a.read (/webapps/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
0|fd     |     at Object.renderToStaticMarkup (/webapps/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:181)
0|fd     |     at renderDocument (/webapps/node_modules/next-server/dist/server/render.js:95:18)
0|fd     |     at Object.renderToHTML (/webapps/node_modules/next-server/dist/server/render.js:238:16)
0|fd     |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by rcalabro** [comment]
Same here with NextJS prod build

```
TypeError: Cannot read property 'setReferenceNode' of undefined
    at Object.children (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/react-popper/lib/cjs/Reference.js:62:33)
    at a.render (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
    at a.read (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToString (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
    at render (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (/Users/rcalabro/Codebase/connect8/packages/glass-web/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/_document.js:359:41)
    at _callee$ (/Users/rcalabro/Codebase/connect8/packages/glass-web/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/_document.js:218:77)
    at tryCatch (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.<computed> [as next] (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/rcalabro/Codebase/connect8/packages/glass-web/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/index.js:446:24)
    at _next (/Users/rcalabro/Codebase/connect8/packages/glass-web/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/index.js:468:9)
    at /Users/rcalabro/Codebase/connect8/packages/glass-web/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/index.js:475:7
    at new Promise (<anonymous>)
    at new F (/Users/rcalabro/Codebase/connect8/packages/glass-web/node_modules/core-js/library/modules/_export.js:36:28)
```

**Comment by rcalabro** [comment]
Same here with NextJS prod build

```
TypeError: Cannot read property 'setReferenceNode' of undefined
    at Object.children (/codebase/myproj/packages/my-app/node_modules/react-popper/lib/cjs/Reference.js:62:33)
    at a.render (/codebase/myproj/packages/my-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
    at a.read (/codebase/myproj/packages/my-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToString (/codebase/myproj/packages/my-app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
    at render (/codebase/myproj/packages/my-app/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/codebase/myproj/packages/my-app/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (/codebase/myproj/packages/my-app/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/_document.js:359:41)
    at _callee$ (/codebase/myproj/packages/my-app/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/_document.js:218:77)
    at tryCatch (/codebase/myproj/packages/my-app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/codebase/myproj/packages/my-app/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.<computed> [as next] (/codebase/myproj/packages/my-app/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/codebase/myproj/packages/my-app/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/index.js:446:24)
    at _next (/codebase/myproj/packages/my-app/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/index.js:468:9)
    at /codebase/myproj/packages/my-app/dist/server/static/LQ6b8oLzlQFB9CSO728R5/pages/index.js:475:7
    at new Promise (<anonymous>)
    at new F (/codebase/myproj/packages/my-app/node_modules/core-js/library/modules/_export.js:36:28)
```

**Comment by virgofx** [comment]
I'm seeing something similar on production builds with Tooltips as well.

**Comment by prasadhewage** [comment]
@rcalabro did you find a solution for this issue?

**Comment by shipcake** [comment]
how to fix ???
