### ISSUE TITLE
UncontrolledCollapse unit test failure, works fine in browser

### ISSUE THREAD

**Issue by akilman** [reactstrap/reactstrap#1532]
- components: `UncontrolledCollapse`
- reactstrap version `#8.0.0`
- import method (unsure)
- react version `#16.8.6`
- bootstrap version `#8.0.0`

### What is happening?

Unit test case is failing in rendering a React Component whose child has an `UncontrolledCollapse` component. Complains of a bogus selector. Otherwise, works fine in the browser.

### What should be happening?

Would expect the component to render and the unit test not fail

### Steps to reproduce issue

1. Clone https://github.com/akilman/reactstrap-collapse-bug
2. `yarn test`

### Error message in console

```
    SyntaxError: '##toggler' is not a valid selector

      at emit (node_modules/nwsapi/src/nwsapi.js:563:17)
      at Object._querySelectorAll [as select] (node_modules/nwsapi/src/nwsapi.js:1492:9)
      at findDOMElements (node_modules/reactstrap/lib/utils.js:239:28)
      at UncontrolledCollapse.componentDidMount (node_modules/reactstrap/lib/UncontrolledCollapse.js:55:48)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:17334:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:18736:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
```

### Code
```jsx
const Example = () => (
  <div>
    <Button color="primary" id="toggler" style={{ marginBottom: '1rem' }}>
      Toggle
    </Button>
    <UncontrolledCollapse toggler="#toggler">
      <Card>
        <CardBody>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt magni, voluptas debitis
          similique porro a molestias consequuntur earum odio officiis natus, amet hic, iste sed
          dignissimos esse fuga! Minus, alias.
        </CardBody>
      </Card>
    </UncontrolledCollapse>
  </div>
);
```

**Comment by justinasit** [comment]
Same issue here as well, any update on this please?

**Comment by TheSharpieOne** [comment]
For this happening during tests check out https://github.com/reactstrap/reactstrap/issues/738#issuecomment-352025434

If it is happening in the browser then at the time the component check the DOM for your target, your target is not yet rendered to the DOM. This is still an issue, but checkout https://github.com/reactstrap/reactstrap/issues/773 for more details.

**Comment by justinasit** [comment]
Ahh thanks @TheSharpieOne, got it to work by following [this](https://github.com/reactstrap/reactstrap/issues/773#issuecomment-373451256) comment.
