### ISSUE TITLE
reactstrap 8.5.0, next.js window not defined

### ISSUE THREAD

**Issue by wegeberg** [reactstrap/reactstrap#1857]
- components: `not known`
- reactstrap version `#8.5.0`
- react version `#16.13.1`
- bootstrap version `#4.5.0`
- next.js version `#9.4.4`

### What is happening?
This is a next.js project.
It crashes when building or running next dev after updating reacstrap from 8.4.1 to 8.5.0
Unable to "next build" as well

### What should be happening?
The app should be able to build and run in dev mode

### Steps to reproduce issue
Clone the repo https://github.com/wegeberg/reacstrap-test.git
-- or --
Create a next.js app using npx create-next-app
npm install bootstrap reactstrap --save
add an _app.js file to the pages directory with this content:
```
import 'bootstrap/dist/css/bootstrap.min.css';
const MyApp = ({ Component, pageProps }) => {
    return <Component {...pageProps} />;
};
export default MyApp;
```
Add some reactstrap component s to pages/index.js
npm run dev
Go to http://localhost:3000

### Error message in console
ReferenceError: window is not defined
    at ..../node_modules/reactstrap/lib/polyfill.js:4:3
    at Object.<anonymous> (..../node_modules/reactstrap/lib/polyfill.js:18:3)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (..../node_modules/reactstrap/lib/index.js:374:41)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///reactstrap:1:18)

### Code
https://github.com/wegeberg/reacstrap-test.git

**Comment by iamandrewluca** [comment]
Do you know why `ReferenceError: window is not defined` is thrown?
Why is `window` missing in the first place? :thinking:

**Comment by wegeberg** [comment]
Hi,

I guess it happens when next.js loads the page server side.
Then windows is not defined.

I've used reactstrap in next.js for a couple of years with no problems so the problem must have occurred in the latest version.

Martin Wegeberg
CTO // Systems Developer

**Comment by iamandrewluca** [comment]
> I guess it happens when next.js loads the page server side.

Ok, makes sense.

> I've used reactstrap in next.js for a couple of years with no problems so the problem must have occurred in the latest version.

That polyfill file was not changed since it was added, I think something was changed in next.js.

As I see there is a PR for this fix. I'll merge it. But in future I think we should drop that `CustomEvent`
