### ISSUE TITLE
Cannot npm run start

### ISSUE THREAD

**Issue by amillward** [reactstrap/reactstrap#2747]
### What is happening?

I have made a fork that I am trying to run so I can contribute. However, when I run `npm run start`, I get the following error;

```
14% building 35/41 modules 6 active /Users/abz/cm/reactstrap/node_modules/core-js/modules/es.array.concat.js/Users/abz/cm/reactstrap/node_modules/@storybook/mdx2-csf/loader.js:23
  const options = Object.assign({}, this.getOptions(), {
                                         ^

TypeError: this.getOptions is not a function
    at Object.loader (/Users/abz/cm/reactstrap/node_modules/@storybook/mdx2-csf/loader.js:23:42)
    at LOADER_EXECUTION (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/abz/cm/reactstrap/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/abz/cm/reactstrap/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/abz/cm/reactstrap/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

I thought to discuss in the slack would be the best thing for support, but the link to get an invite to slack is a dead end.

### What should be happening?

Storybook should run when executing `npm run start`

### Steps to reproduce issue

1. clone master
2. run `npm run start`

### Error message in console

```
14% building 35/41 modules 6 active /Users/abz/cm/reactstrap/node_modules/core-js/modules/es.array.concat.js/Users/abz/cm/reactstrap/node_modules/@storybook/mdx2-csf/loader.js:23
  const options = Object.assign({}, this.getOptions(), {
                                         ^

TypeError: this.getOptions is not a function
    at Object.loader (/Users/abz/cm/reactstrap/node_modules/@storybook/mdx2-csf/loader.js:23:42)
    at LOADER_EXECUTION (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/abz/cm/reactstrap/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/abz/cm/reactstrap/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/abz/cm/reactstrap/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/abz/cm/reactstrap/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

### Code

No code changes to master

**Comment by amrinder1189** [comment]
Hi , can you please try npm start or yarn start ?

**Comment by amillward** [comment]
Same error sadly
<img width="898" alt="Screenshot 2023-05-13 at 16 13 02" src="https://github.com/reactstrap/reactstrap/assets/1857493/aaf39bc3-fdbf-45e1-9ee9-a2139872bf89">

**Comment by illiteratewriter** [comment]
Can you let me know the version of Node you're using? 

I'm Currently using Node 16, so can you try on Node 16?

**Comment by amillward** [comment]
thanks - I'm on 16.20.0

**Comment by amillward** [comment]
I've just run 
```
rm -rf node_modules
npm i
npm start
```

and now getting a different error 🤦🏻‍♀️

```
ERROR in ./stories/examples/Props.js
Module not found: Error: Can't resolve '@storybook/addon-docs' in '/Users/abz/cm/reactstrap/stories/examples'
 @ ./stories/examples/Props.js 4:0-50 13:26-35
 @ ./stories/examples/Breadcrump/Props.js
 @ ./stories/Breadcrumb.stories.js
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.cjs-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

**Comment by illiteratewriter** [comment]
Can you do `yarn` instead of npm?

```
rm -rf node_modules
yarn
yarn start
```

**Comment by amillward** [comment]
Success.

I do get warnings from yarn about these as being missing packages/unmet peer deps though

```
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/components@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/core-events@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/theming@^6.3.0".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > eslint-config-airbnb@19.0.4" has unmet peer dependency "eslint-plugin-react-hooks@^4.3.0".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
```


Now to go and learn yarn I guess... 😁

**Comment by illiteratewriter** [comment]
When using `npm` or `yarn`, these package managers generate `package-lock.json` (generated by `npm`) or `yarn.lock`(generated by `npm`) files. These files help the package managers to resolve the correct dependencies. The issue you encountered was, Reactstrap uses `yarn` and when you tried to use `npm`, `npm` couldn't figure out the correct dependencies leading to the issue which you encountered.

The warnings are because the [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies) are not installed, which you can safely ignore for the time being. Sometimes you might need to install the peer dependencies manually, but that's not the case here. 

Happy that your issue got fixed, and looking forward to PRs from you. :)
