### ISSUE TITLE
Warning: Failed prop type: The prop `transition.timeout` is marked as required in `PopperContent2`, but its value is `undefined`.

### ISSUE THREAD

**Issue by dardoguidobono** [reactstrap/reactstrap#2819]
- components: `UncontrolledTooltip`
- reactstrap version `#9.2.3`
- import method `umd/csj/es` 
- react version `#18.2.0`
- bootstrap version `#5.3.3`

### What is happening?
Warning: Failed prop type: The prop `transition.timeout` is marked as required in `PopperContent2`, but its value is `undefined`.
    at PopperContent2 (http://oregondevel:3000/node_modules/.vite/deps/reactstrap.js?v=0d7d2c2d:6493:5)
    at TooltipPopoverWrapper2 (http://oregondevel:3000/node_modules/.vite/deps/reactstrap.js?v=0d7d2c2d:6806:5)
    at Tooltip (http://oregondevel:3000/node_modules/.vite/deps/reactstrap.js?v=0d7d2c2d:8520:78)
    at UncontrolledTooltip2 (http://oregondevel:3000/node_modules/.vite/deps/reactstrap.js?v=0d7d2c2d:12358:5)

Tooltip is triggered but warning raised

### Steps to reproduce issue

1. ...
2. ...

### Error message in console

```
paste error message with stacktrack here
```

**Comment by mike-lock** [comment]
We have the same warning.

**Comment by shadi-golroonia** [comment]
we have this warning too

**Comment by alextselegidis** [comment]
+1

**Comment by neurobug** [comment]
+1

**Comment by cm253** [comment]
+1

**Comment by vladdg-dev** [comment]
This issue will never be solved, the maintainers are lazy and inactive

**Comment by matttk** [comment]
That’s the beauty of open source. If you’re so much harder working, you can
solve it yourself.

**Comment by arieled91** [comment]
I'm having this issue with the `PopperContent` and `Fade` components. 

- ```The prop `timeout` is marked as required in `Fade`, but its value is `undefined`.```
- ```The prop `transition.timeout` is marked as required in `PopperContent`, but its value is `undefined`.```

**Comment by arieled91** [comment]
I just installed `10.0.1-release-v10.0.0-c659629.0`, and the issue seems to be solved there. Is it possible to release V10 soon?

**Comment by aman-knight** [comment]
any solutions for this ?

**Comment by vinayv-456** [comment]
@illiteratewriter  default props of fade compoent are removed to avoid "deafult props are  deprecated warning in functional components" leading to undefined warnings where the prop is required.
removal of props are done for [this issue ](https://github.com/reactstrap/reactstrap/issues/2801 )

**Comment by kacperpaczos** [comment]
What can I do to resolve this problem? Maybe downgrade?

**Comment by renjie-run** [comment]
Same issue, any solutions for this ?

**Comment by Michael18811380328** [comment]
Same issue, any solutions for this ? Hope to release new version to solve this issue.

**Comment by kennethsato** [comment]
+1

**Comment by The-Luc** [comment]
+1

**Comment by dollyzn** [comment]
+1

**Comment by antonina-fms** [comment]
Warning: Failed prop type: The prop `timeout` is marked as required in `Fade`, but its value is `undefined`.

**Comment by amillward** [comment]
I fixed this in my case by passing `transition={{ timeout: 300 }}` to my `<Alert />` and `fade={{ timeout: 300 }}` to my `<UncontrolledTooltip />`

**Comment by ruben-rodrigues** [comment]
> I fixed this in my case by passing `transition={{ timeout: 300 }}` to my `<Alert />` and `fade={{ timeout: 300 }}` to my `<UncontrolledTooltip />`

Did you really fix it for UncontrolledTooltip? The tooltip components use the TooltipPopoverWrapper component that is not forwarding the `transition` prop to PopperContent, thus the "The prop transition.timeout is marked as required in PopperContent, but its value is undefined". `fade` is a boolean (you suggested passing `fade={{ timeout: 300 }}`), so not sure how that would fix it, as the warning is related to prop types of PopperContent.

Thanks!

**Comment by amalpradeep** [comment]
We can fix this warning by disabling the fade animation:

```jsx
<Alert color="danger" fade={false}>
  Alert without fade
</Alert>

**Comment by SaloniYrj** [comment]
react.development.js:187 Warning: Failed prop type: The prop `transition.timeout` is marked as required in `PopperContent`, but its value is `undefined`.
    at PopperContent (http://localhost:4007/static/js/vendors-node_modules_reactstrap_esm_UncontrolledTooltip_js.chunk.js:274:5)
    at TooltipPopoverWrapper (http://localhost:4007/static/js/vendors-node_modules_reactstrap_esm_UncontrolledTooltip_js.chunk.js:681:5)
    at Tooltip (http://localhost:4007/static/js/vendors-node_modules_reactstrap_esm_UncontrolledTooltip_js.chunk.js:476:95)
    at UncontrolledTooltip (http://localhost:4007/static/js/vendors-node_modules_reactstrap_esm_UncontrolledTooltip_js.chunk.js:1175:5)  i passed the transition={{ timeout: 300 }}
						fade={{ timeout: 300 }} these as well still same issue persist

**Comment by alamothe** [comment]
Any updates?

**Comment by waldifubu** [comment]
I am also interested what to do to fix it

**Comment by Michael18811380328** [comment]
I hope the development team can fix this issue as soon as possible, as it hasn't been updated for 2 years.

**Comment by matttk** [comment]
@Michael18811380328 our solution was to cut reactstrap out of our project. It was a big undertaking, but it was time to move on.

**Comment by Michael18811380328** [comment]
> [@Michael18811380328](https://github.com/Michael18811380328) our solution was to cut reactstrap out of our project. It was a big undertaking, but it was time to move on.

@matttk Hello matttk, thank you for your suggestion. We have already used React in over a dozen projects, and changing to other components in the short term would be more costly.

**Comment by rj-david** [comment]
Our solution for this issue is to use reactstrap version 9.2.2
