### ISSUE TITLE
Failed prop type 'timeout'

### ISSUE THREAD

**Issue by CamdenTadhg** [reactstrap/reactstrap#2823]
- components: Tooltip
- reactstrap version `#9.2.3`
- import method `umd/csj/es` not sure
- react version `#18.3.1`
- bootstrap version `#5.3.3`

### What is happening?

I'm getting two warnings.  "Failed prop type: The prop 'transition.timeout' is marked as required in PopperContent2 but its value is undefined" which references at PopperContent2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:10385:5) 
 and "Failed prop type: The prop 'timeout' is marked as required in Fade but its value is undefined"  which references at Fade (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:7309:39)

### What should be happening?

I'm sorry. I'm a real beginner so I'm not sure I'm doing this right. I think there's an issue in the reactstrap code that is causing these problems because they don't appear to reference any code I've written. The tooltip still works, though it doesn't timeout, which I'm happy with but maybe it's supposed to? 

### Steps to reproduce issue

It came up when I opened a modal that had a tooltip component in it. 

### Error message in console

```
hook.js:608 Warning: Failed prop type: The prop `transition.timeout` is marked as required in `PopperContent2`, but its value is `undefined`.
    at PopperContent2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:10385:5)
    at TooltipPopoverWrapper2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:10698:5)
    at Tooltip (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:12412:78)
    at div
    at Col (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:1602:25)
    at div
    at FormGroup (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:12908:25)
    at form
    at Form2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:12746:5)
    at DiagnosisForm (http://localhost:5173/src/components/DiagnosisForm.jsx?t=1731452167789:24:26)
    at div
    at div
    at div
    at Transition2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:6068:30)
    at Fade (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:7309:39)
    at div
    at Portal2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:11566:5)
    at Modal2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:11816:5)
    at div
    at Row (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:1474:25)
    at div
    at Container (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:1397:25)
    at Profile (http://localhost:5173/src/components/Profile.jsx?t=1731452167789:29:20)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4069:5)
    at Outlet (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4475:26)
    at ProtectedRoute (http://localhost:5173/src/components/ProtectedRoutes.jsx:23:23)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4069:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4539:5)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4482:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:5228:5)
    at App
    at Provider (http://localhost:5173/node_modules/.vite/deps/react-redux.js?v=7cbb2ce3:1097:3)

hook.js:608 Warning: Failed prop type: The prop `timeout` is marked as required in `Fade`, but its value is `undefined`.
    at Fade (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:7309:39)
    at PopperContent2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:10385:5)
    at TooltipPopoverWrapper2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:10698:5)
    at Tooltip (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:12412:78)
    at div
    at Col (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:1602:25)
    at div
    at FormGroup (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:12908:25)
    at form
    at Form2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:12746:5)
    at DiagnosisForm (http://localhost:5173/src/components/DiagnosisForm.jsx?t=1731452167789:24:26)
    at div
    at div
    at div
    at Transition2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:6068:30)
    at Fade (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:7309:39)
    at div
    at Portal2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:11566:5)
    at Modal2 (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:11816:5)
    at div
    at Row (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:1474:25)
    at div
    at Container (http://localhost:5173/node_modules/.vite/deps/reactstrap.js?v=7cbb2ce3:1397:25)
    at Profile (http://localhost:5173/src/components/Profile.jsx?t=1731452167789:29:20)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4069:5)
    at Outlet (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4475:26)
    at ProtectedRoute (http://localhost:5173/src/components/ProtectedRoutes.jsx:23:23)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4069:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4539:5)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:4482:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=7cbb2ce3:5228:5)
    at App
    at Provider (http://localhost:5173/node_modules/.vite/deps/react-redux.js?v=7cbb2ce3:1097:3)
```

**Comment by s-h-a-d-o-w** [comment]
It's already being discussed here: https://github.com/reactstrap/reactstrap/issues/2819
