### ISSUE TITLE
InputGroupText on ServerSideError gives TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by ste9206** [reactstrap/reactstrap#878]
Hi...I'm using reactstrap 5.0.0-alpha.4 in a component with:
- React and ReactDOM 16.2.0 
- react-transition-group: "^2.2.1"
-    reactstrap-tether: "^1.3.4",
-  react-popper: "^0.8.2"

I'm using server-side rendering. With normal client-side this works, but if I use ssr, with this render():
```
render(){       
        return (
            <div className="app flex-row align-items-center">
        <Container>
          <Row className="justify-content-center">
            <Col md="8">
              <CardGroup>
                <Card className="p-4">
                  <CardBody>
                    <h1>Login</h1>
                    <p className="text-muted">Sign In to your account</p>
                    <InputGroup className="mb-3">
                      <InputGroupAddon  className='input-group-prepend'>
                      <InputGroupText>
                          <i className="icon-user"></i>
                        </InputGroupText>
                      </InputGroupAddon>
                      <Input type="text" placeholder="Username" name="user" />
                    </InputGroup>
                    <InputGroup className="mb-4">
                      <InputGroupAddon  className='input-group-prepend'>
                        <InputGroupText>
                          <i className="icon-lock"></i>
                        </InputGroupText>
                      </InputGroupAddon>
                      <Input type="password" placeholder="Password"/>
                    </InputGroup>
                    <Row>
                      <Col xs="6">
                        <Button color="primary" className="px-4">Login</Button>
                      </Col>
                      <Col xs="6" className="text-right">
                        <Button color="link" className="px-0">Forgot password?</Button>
                      </Col>
                    </Row>
                  </CardBody>
                </Card>
                <Card className="text-white bg-primary py-5 d-md-down-none" style={{ width: 44 + '%' }}>
                  <CardBody className="text-center">
                    <div>
                      <h2>Sign up</h2>
                      <Button color="primary" className="mt-3" active>Register</Button>
                    </div>
                  </CardBody>
                </Card>
              </CardGroup>
            </Col>
          </Row>
        </Container>
      </div>

        );

```
I obtain this error:
```
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at ReactDOMServerRenderer.renderDOM (/Users/stefano/Desktop/ai/node_modules/react-dom/cjs/react-dom-server.node.development.js:2304:28)
    at ReactDOMServerRenderer.render (/Users/stefano/Desktop/ai/node_modules/react-dom/cjs/react-dom-server.node.development.js:2298:21)
    at ReactDOMServerRenderer.read (/Users/stefano/Desktop/ai/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at Object.renderToString (/Users/stefano/Desktop/ai/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at then.e (/Users/stefano/Desktop/ai/dist/server/index.js:24:541)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:2502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

```
I've found that error happens with InputGroupText...without it works but graphic is horrible, instead of client-side.

My server-side render is:
```
    const initialState = {component:'Login'};
                const markup = ReactDOM.renderToString( <App {...initialState} />);
            
                res.send(generateHtml(markup,initialState));

```

and it doesn't give other problems. I use parcel-bundler instead of webpack.
How to fix this issue?

**Comment by GoPro16** [comment]
This seems like an issue with how you are importing vs the library itself. I would search on that specific issue and then come back if anything persists. Given its SSR has came a long way since then.
